FROM python:3.6-alpine

RUN mkdir /TechnicalTest

WORKDIR /TechnicalTest

COPY requirements.txt .

# Adds dependencies to build psycopg2
RUN \
    apk add --no-cache postgresql-libs && \
    apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
    pip install -r requirements.txt --no-cache-dir && \
    apk --purge del .build-deps

COPY . .

CMD python ./app.py